url: "https://orientamento.lecosimo.it" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site
title: "Liceo C. De Giorgi" # the name of your site
lang: "it-IT"

# SEO
tagline: "Il Liceo De Giorgi si presenta al pubblico"
description: "Sei un ragazzo delle scuole medie? Vieni a trovarci per informazioni sulla scuola, la didattica e i docenti."

# Developing settings
livereload: true # Autoreload on change
host: 0.0.0.0 # Serve to all local network devices

plugins:
  - jekyll-sitemap