---
title: Liceo C. De Giorgi
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://orientamento.lecosimo.it
baseurl: ''
lang: it-IT
tagline: Il Liceo De Giorgi si presenta al pubblico
description: Sei un ragazzo delle scuole medie? Vieni a trovarci per informazioni
  sulla scuola, la didattica e i docenti.
livereload: true
host: 0.0.0.0
plugins:
- jekyll-sitemap
